### ISSUE TITLE
i don't get a change track button in homekit

### ISSUE THREAD

**Issue by sanojjonas** [ebaauw/homebridge-music#10]
i don't get a change track button homekit. 
it would also be nice if itunes would pause in stead of stop when you turn off/on itunes via homekit.

**Comment by ebaauw** [comment]
> i don't get a change track button homekit.

Apple's Home app doesn't support custom characteristics.  You need to use another HomeKit app, see https://github.com/ebaauw/homebridge-music#caveats.

> it would also be nice if itunes would pause in stead of stop when you turn off/on itunes via homekit.

You can create your own Applescript file to achieve that.  Just copy `iTunes.applescript` to `myScript.applescript` and change:
https://github.com/ebaauw/homebridge-music/blob/3b52073959ae7b2292433131b0207ec4cc86dfb5/scripts/iTunes.applescript#L27
Run `make myScript.scpt` or `osascript -o myScript.scpt myScript.applescript` to compile the script.  To use it, add `"script": "myScript"` to config.json.
