### ISSUE TITLE
Preventing iTunes to start

### ISSUE THREAD

**Issue by Psychopatient** [ebaauw/homebridge-music#11]
I was looking a long time for a possibility to integrate airfoil in HomeKit. I was more than happy to find this plugin, so thank you for your effort and good work. 
Like i said, i just use this for airfoil, but every time i run it, iTunes starts. Is there was to prevent iTunes from starting?

**Comment by ebaauw** [comment]
Interesting idea.  homebridge-music exposes a player and speakers, I don’t think it will work without a player.  The actual interface to the player and speakers is through Applescript, see 
https://github.com/ebaauw/homebridge-music#applescript.  You might be able to copy and modify the Airfoil script not to call iTunes and return dummy values for the player.  Or maybe use Airfoil for the player as well.
