### ISSUE TITLE
AirFoil 5.8.8 AppleScript errors

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-music#13]
The Airfoil and EyeTV scripts no longer work with AirFoil 5.8.8.  It seems this version of AirFoil has broken AppleScript support.  I've logged an issue with RogueAmoeba support.

If you've already upgraded, you can download 5.8.6 [here](https://rogueamoeba.com/legacy/#airfoilformac).  I don't think 5.8.7 is available for download any more.

**Comment by ebaauw** [comment]
Got a swift reply from Rogue Amoeba support.  They've acknowledged the issue with 5.8.8 and will fix it with 5.8.9.  A developer preview can be found at https://rogueamoeba.com/airfoil/mac/download-development.php.

**Comment by yaggayoyo** [comment]
How do you control AirFoil speakers separately from iTunes?

**Comment by ebaauw** [comment]
Thru the AirFoil app.  See https://rogueamoeba.com/airfoil/mac/.

**Comment by ebaauw** [comment]
Fixed in AirFoil 5.9.1.  I find it takes some time before the AppleScript returns, so you might want to set `"timeout": 10` in config.json.
