### ISSUE TITLE
unsupported engine

### ISSUE THREAD

**Issue by platini76** [ebaauw/homebridge-music#22]
in installation there is an error unsupported engine.

**Comment by donavanbecker** [comment]
@platini76 can you provide logs? and your system info?

**Comment by ebaauw** [comment]
Are you installing homebridge-music on macOS?

**Comment by platini76** [comment]
no through homebridge conif ui x    on linux

**Comment by platini76** [comment]
I see now only for mac os... so please inform config-ui-x that your plugin appear on their install page.
