### ISSUE TITLE
0.2.27 not on npm?

### ISSUE THREAD

**Issue by DJay-X** [ebaauw/homebridge-music#23]
Not sure if it's only on my side because I hear no other complaints. :)
Is 0.2.27 still not on npm?

Thanks again for your work and time @ebaauw

**Comment by ebaauw** [comment]
Indeed, it seems I forgot to publish it.  Just did.

Will publish a new release later this week, when new patch release of NodeJS will be out.

**Comment by DJay-X** [comment]
Thanks a lot. 👍 
Now I'm on 0.2.27 with Node v12.18.3, npm v6.14.6 on macOS Catalina.
