### ISSUE TITLE
Installation issue.

### ISSUE THREAD

**Issue by sdorilas** [ebaauw/homebridge-music#25]
Please assist in regards in what I need to do:

pi@homebridge:/var/lib/homebridge $ sudo npm -g i homebridge-music
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'homebridge-music@0.4.23',
npm WARN EBADENGINE   required: { homebridge: '^1.5.0', node: '^16.16.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.2', npm: '8.14.0' }
npm WARN EBADENGINE }
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for homebridge-music@0.4.23: wanted {"os":"darwin"} (current: {"os":"linux","arch":"arm"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: arm

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-16T20_37_48_765Z-debug-0.log
pi@homebridge:/var/lib/homebridge $

**Comment by ebaauw** [comment]
Read the prerequisites: Homebridge Music only runs on macOS.
