### ISSUE TITLE
No iTunes player 

### ISSUE THREAD

**Issue by maxymkov** [ebaauw/homebridge-music#28]
In legacy macOS usage of iTunes script leads to error, as Apple replaces iTunes with Music on legacy macOS too. 
I changed the script, but for some users it might be not so obvious, what they should do in order to make plugin work.

**Comment by ebaauw** [comment]
Hm, interesting.  What version of macOS do you have?

It's just a simple config.json setting, `script`.  I suppose, I could change the default script library to `Music` for all versions of macOS.

**Comment by maxymkov** [comment]
> Hm, interesting. What version of macOS do you have?
> 
> It's just a simple config.json setting, `script`. I suppose, I could change the default script library to `Music` for all versions of macOS.

I’m very sorry. I was blind and didn’t check my os version in advance. I have 12.7 so my message was irrelevant. I was so sure my os is below 10.15 so even didn’t check before leaving comment. 
Sorry again.
