### ISSUE TITLE
Applescript Error: Music: could not set on to true

### ISSUE THREAD

**Issue by jimRoper** [ebaauw/homebridge-music#6]
Receiving an error on the current version of iTunes/macOS.
(macOS High Sierra version 10.13.5 (17F77), iTunes 12.7.5.9)
homebridge-music v0.1.7, node v10.4.1, homebridge v0.4.43

**[6/24/2018, 1:07:23 PM] [Music]** Music: set on from false to true
**[6/24/2018, 1:07:23 PM] [Music]** applescript error execution error: iTunes got an error: Can’t make some data into the expected type. (-1700)
**[6/24/2018, 1:07:23 PM] [Music]** applescript: set lib to (load script "/usr/local/lib/node_modules/homebridge-music/scripts/iTunes.scpt") tell lib to setPlayerOn(true, "")
**[6/24/2018, 1:07:23 PM] [Music]** Music: could not set on to true

**Comment by ebaauw** [comment]
This happens when there's no current track in iTunes.  Set `"track"` in config.json to specify a default track.

**Comment by jimRoper** [comment]
Aah!  Thanks for the quick reply and the good work!
